[package]
name = "kriss"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
kiddo = "4.2.1"
log = "0.4.22"
nalgebra = "0.33.0"
nalgebra-lapack = { version = "0.25.0"}
petgraph = "0.6.5"
rustworkx-core = "0.15.1"

[dev-dependencies]
all_asserts = "2.3.1"
